{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory vs Time on Namespace Level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Memory (MB)" }
   ],
   "targets": [
    {
     "expr": "namespace_name:kube_pod_container_resource_requests_memory_bytes:sum/1E6",
     "legendFormat": "{{name_space}}"
    }
   ]
  },
  {
   "title": "Container Count vs Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of Containers" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Memory vs Time on Container Level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Memory (MB)" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=~\"microservice|filebeat|logstash|elasticsearch|kibana\"}/1E6",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}