apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
    nodePort: 30000
  selector:
    name: kibana
  type: NodePort